# Emanuel Ramos
# 11/15/2022
#
# Description: makes a list of random numbers and then multiplies all the numbers within the list

import random

# create a list were we will store the numbers generated by a for loop
Number_List = []

# for loop that generates 10 random numbers
for num in range(1, 11):  # <-- change range to make more random numbers
    # add the random number into the list every go through the loop
    Number_List.append(random.randint(1, 100))  # <-- change range to make a list less or more extensive
# show the user the 10 random numbers generated
print(Number_List)


# make a function to multiply all the numbers within a list
def multiplylist(list_of_numbers):
    # multiply the first number by 1 so we get itself
    answer = 1
    # for loop that multiplies each number in list by the previous number
    # the first time it runs it will multiply the first number in the list by 1
    # then answer will be changed to a different number
    for number in list_of_numbers:
        # equation stating that answer will be multiplied by the number in the list
        # and then assign a new value to answer
        answer = answer * number
    return answer


# this calls upon the execution of the function we created with the numbers
# randomly generated in the for loop in line 12
print(multiplylist(Number_List))


# you can make a list with numbers you want multiplied by making a new list
# and calling to the function I created
# for example:
# new_list = [20, 30, 40, 17, 26]
# print(multiplylist(new_list))
