# Emanuel Ramos
# 11/15/2022
#
# Description: organizes a list of numbers to only display unique numbers, no repeated numbers

import random

# create a list were we will store the numbers generated by a for loop
Number_List = []

# for loop that generates 10 random numbers
for num in range(1, 11):  # <-- change range to make more random numbers
    # add the random number into the list every go through the loop
    Number_List.append(random.randint(1, 5))  # <-- change range to make a list less or more extensive
# show the user the 10 random numbers generated
print(Number_List)


# create a function that creates a list with only unique numbers
def unique_number_list(list_of_numbers):
    # create a new list where we can store the unique numbers
    unique_list = []
    # create a for loop that will go through all the numbers in the list and return only the unique numbers
    for number in list_of_numbers:
        # if the current number in the loop is already in unique_list then continue to the next number in the list
        if number in unique_list:
            continue
        # if the current number in the loop isn't in the unique_list then add it to the end of unique_list
        else:
            unique_list.append(number)
    return unique_list


# use the function we created on line 20 - 31 to organize the randomly generated list of numbers we created
print(unique_number_list(Number_List))


# you can make a list with numbers you want organized by making a new list
# and calling to the function I created
# for example:
# new_list = [1, 3, 3, 3, 6, 2, 3, 5]
# print(unique_number_list(new_list))
